Development of the Nytime Clone ready for a Merge to Master
dannisonarias/Positioning-And-Floating-Elements pull request #1
Opened 2020-01-21 21:46 UTC by dannisonarias

Thanks for reviewing our project
We followed the guidelines as closely as possible! 
all elements are aligned with floats.

2020-01-21 22:23 UTC, mosesogwo requested changes
**:clap: Great job team, a few changes and we will be good to :airplane:**
1. Linter tests are failing. Ensure that you address all the linter errors.
![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png)


2. The new york times logo in the nav bar should be centered.
Compare yours with this:
![image](https://user-images.githubusercontent.com/46611870/72848412-cecbfe80-3ca4-11ea-8fdb-d61350a660f1.png)


3. Wrap the main navigation links in `nav` tags.
![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/semantic_html_requirement.png)


4. The background image in the **Theory of Inflation section** does not display in the live demo. Check how the image is referenced in your css. Probably, you have an unnecessary preceding slash before the file address.

Kindly make these changes and submit another code review request.
**Happy Coding :smile:**

**Status: Changes requested**

2020-01-22 18:37 UTC, pelzolga123 commented on index.html
> +        <li><a id="footer-bottom-nav-a" href="#">Subscriptions</a></li>
There should be no ID selectors for multiple elements, ID should be unique for each element, better use class instead.

2020-01-22 18:37 UTC, pelzolga123 requested changes
Project requires changes.

2020-01-22 18:37 UTC, pelzolga123 commented
## Hi Team! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your project looks :+1: amazing!
* [ ] Check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload). Now it shows errors in your project.
##### Navbar part
* [ ] The NY Times logo should be a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
##### Bottom part
* [ ] Should contain links to other articles with image previews on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-01-22 19:52 UTC, addod19 commented
## Pull Request under ***review*** by Daniel Larbi Addo (TSE)

2020-01-22 20:03 UTC, addod19 requested changes
## Status: Require changes 🔴

Hi Team ✋ 
Good job fixing the changes requested by previous reviewers.

Kindly fix linter errors and submit code review. Linters are still failing

![slint](https://user-images.githubusercontent.com/46388113/72929518-e2816e80-3d51-11ea-977c-446d75306a16.jpg)

Kindly fix these and submit code review. 👍 
Happy coding 💻 

[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo-9738b0128/)

2020-01-22 20:07 UTC, addod19 commented
Kindly change the hamburger to button....Currently it is image

2020-01-22 23:35 UTC, Anna-Myzukina commented
### Pull Request under the review by Anna Muzykina (TSE)

2020-01-22 23:41 UTC, Anna-Myzukina commented
# Status [APPROVED]
## Great job on working on all requirements :+1: 


Go ahead and merge to master.
Good luck in your next project Happy coding

2020-01-22 23:43 UTC, merged